version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: untitledapp
    container_name: app
    restart: unless-stopped
    volumes:
      - ./:/var/www

  webserver:
    build:
     context: .
     dockerfile: Dockerfile_Nginx
    image: nginx
    container_name: webserver
    ports:
    - "8080:80"
    volumes:
    - ./:/var/www
    - ./config/nginx/:/etc/nginx/conf.d/
    depends_on:
    - app

  db:
    image: mysql:5.7.22
    container_name: db
    environment:
      MYSQL_DATABASE: DockerDB
      MYSQL_ROOT_PASSWORD: pa55word
    ports:
    -  "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
    dbdata:
      driver: local